### ISSUE TITLE
Fetching gcdump gives System.ApplicationException: RootIndex not set Error

### ISSUE THREAD

**Issue by kavitap081** [JaneySprings/DotNet.Meteor#104]
Hello,

Getting error when fetching gcdump for subsequent flows .
Steps :
1. Perform some flows in the application.
2. Fetch gcdump using command /dump, .gcdump is fetched successfully.
3. Continue the execution once fetching completed i.e."Finished writing xyz bytes" comes on Debug console.
4. Perform few more flows and fetch gcdump again with command /dump
5. It gives  this error
6. Now, restart execution and error is gone.
But I need snapshots in real time to compare dump files, please let me know how can this be resolved.

ERROR] System.ApplicationException: RootIndex not set.
   at Graphs.Graph.AllowReading() in /Users/nromanov/Work/DotNet.Meteor/src/DotNet.Diagnostics/src/Tools/dotnet-gcdump/DotNetHeapDump/Graph.cs:line 241
   at Graphs.MemoryGraph.AllowReading() in /Users/nromanov/Work/DotNet.Meteor/src/DotNet.Diagnostics/src/Tools/dotnet-gcdump/DotNetHeapDump/MemoryGraph.cs:line 100
   at Microsoft.Diagnostics.Tools.GCDump.CollectCommandHandler.TryCollectMemoryGraph(CancellationToken ct, Int32 processId, String diagnosticPort, Int32 timeout, Boolean verbose, MemoryGraph& memoryGraph) in /Users/nromanov/Work/DotNet.Meteor/src/DotNet.Diagnostics/src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs:line 153
   at Microsoft.Diagnostics.Tools.GCDump.CollectCommandHandler.<>c__DisplayClass4_0.<Collect>b__0() in /Users/nromanov/Work/DotNet.Meteor/src/DotNet.Diagnostics/src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs:line 100
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Diagnostics.Tools.GCDump.CollectCommandHandler.Collect(CancellationToken ct, Int32 processId, String output, String diagnosticPort) in /Users/nromanov/Work/DotNet.Meteor/src/DotNet.Diagnostics/src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs:line 109

**Comment by JaneySprings** [comment]
Hi @kavitap081 ! Can you repost this issue to [.NET Diagnostics](https://github.com/dotnet/diagnostics/issues)? I think there are people out there who are better at this =)

**Comment by JaneySprings** [comment]
I found a solution, I will try to fix it as soon as possible!
