### ISSUE TITLE
Cannot Debug On iOS Device After Installing .NET iOS 18.1.9163

### ISSUE THREAD

**Issue by mlancione** [JaneySprings/DotNet.Meteor#146]
Getting the following Debug Console output when debugging on an iOS device after installing .NET iOS 18.1.9163 (released today):

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net9.0_18.1/18.1.9163/tools/bin/mlaunch
2
error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.NotSupportedException: Specified method is not supported.
at Xamarin.Hosting.DeviceCtlDevice.CreateTcpTunnel(LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceCtlDevice.cs:line 79
at Xamarin.Launcher.DevController.CreateTcpTunnel(String, LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 844
at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 536
at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 443
at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 130
System.NotSupportedException: Specified method is not supported.
at Xamarin.Hosting.DeviceCtlDevice.CreateTcpTunnel(LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceCtlDevice.cs:line 79
at Xamarin.Launcher.DevController.CreateTcpTunnel(String, LaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 844
at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 536
at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 443
at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 130
```

**Comment by mlancione** [comment]
These 2 .net changes could be related:
https://github.com/xamarin/xamarin-macios/commit/3d4ea05b55247501ebd204cc4efb71ffd5d92d46
https://github.com/xamarin/xamarin-macios/commit/5b695a30fe8eb3f2b0bd3a5621bb0c8b62a01975

**Comment by JaneySprings** [comment]
Hi, @mlancione! Yes, something changes in the iOS workload.

https://github.com/xamarin/xamarin-macios/issues/21664#issuecomment-2503048477

**Comment by JaneySprings** [comment]
@mlancione, I have created a `6.1.3` hotfix. I'm not sure that it is correct fix but it works for now =)

I will leave this issue opened until official solution.

**Comment by mlancione** [comment]
@JaneySprings Thanks for the quick fix! As always, your support is excellent! I can report that the debugging is working again with your change.

One side question, is it possible to display the output of the deployment progress while the app is being uploaded to the device? VS Mac used to show a console output with percentages.

**Comment by JaneySprings** [comment]
I use `mlaunch --installdev`:
https://github.com/JaneySprings/DotNet.Meteor/blob/20a49295c0246c5eb540daffb766e7a5339d3233/src/DotNet.Meteor.Common/Apple/MonoLauncher.cs#L16-L23
and I don't know if it supports this functionality because this tool is closed-source.
Usually I look at circle progress on iOS device.

**Comment by mlancione** [comment]
According to this commit there may be an "-install-progress" argument that can be used? If it works maybe you can add it as an optional feature?
https://github.com/xamarin/xamarin-macios/pull/1483

**Comment by JaneySprings** [comment]
Yes, it works, but we also need to disable `device-ctl` for installation.
```cs
new ProcessRunner(tool, new ProcessArgumentBuilder()
            .Append( "--installdev").AppendQuoted(bundlePath)
            .Append($"--devname={serial}")
            .Append( "--install-progress")
            .Append( "--use-device-ctl=false"), logger)
            .WaitForExit();
 ```
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/89898ed1-9417-4091-8fdf-23dc15c67557">

**Comment by mlancione** [comment]
I think that looks great. Will help to monitor deployment status.

**Comment by JaneySprings** [comment]
Added in `6.1.4`!
